# alacritty.toml

[general]
import = ["~/.config/alacritty/themes/themes/tomorrow_night"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "SemiLight" }
size = 13

[terminal.shell]
program = "/usr/bin/fish"
# program = "/home/linuxbrew/.linuxbrew/bin/nu"

[mouse]
bindings = [
  { mouse = "Middle", action = "PasteSelection" }
]

